// Wrap HardwareRenderer

#pragma once
#include "Renderer.hpp"
#include <iostream>

// Include Verilator headers (generated by Verilator from Chisel)
#include "VRenderer.h" 
#include "verilated.h"

class HardwareRenderer : public Renderer {
private:
    VRenderer* top;

public:
    HardwareRenderer() {
        top = new VRenderer;
        top->reset = 1;
        top->clock = 0;
        tick();
        top->reset = 0;
    }

    ~HardwareRenderer() {
        top->final();
        delete top;
    }

    void tick() {
        top->clock = 0; top->eval();
        top->clock = 1; top->eval();
    }

    void draw(fb_id_t fb_id, ap_uint<128>* vram, int angle) override {
        top->io_start = 1;
        top->io_angle = angle;
        top->io_fb_id = fb_id; 

        bool done = false;
        int timeout = 1000000;

        while (!done && timeout > 0) {
            tick();
            top->io_start = 0; 

            // Memory Write Emulation
            if (top->io_mem_we) {
                uint32_t addr = top->io_mem_addr;
                
                // Reconstruct 128-bit data from Verilator's WData array
                ap_uint<128> data = 0;
                data |= (ap_uint<128>)top->io_mem_wdata[0];
                data |= ((ap_uint<128>)top->io_mem_wdata[1]) << 32;
                data |= ((ap_uint<128>)top->io_mem_wdata[2]) << 64;
                data |= ((ap_uint<128>)top->io_mem_wdata[3]) << 96;

                vram[addr] = data;
            }

            if (top->io_done) done = true;
            timeout--;
        }
    }
};